name: 'STK CLI Action'

description: 'Github Action to install STK CLI'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Install jq, curl, zip, and git
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl zip git

    - name: Install STK CLI
      run: |
        cd /tmp
        curl -fsSL https://stk.stackspot.com/install.sh | bash
        echo "~/.stk/bin" >> $GITHUB_PATH
      shell: bash

    - name: Login to StackSpot Account
      run: stk login --client-id=${{ inputs.client_id }} --client-key=${{ inputs.client_key }} --realm=${{ inputs.realm }}  
      shell: bash

    - name: Show STK CLI version
      run: stk --version     

branding:
    icon: 'terminal'
    color: 'gray-dark'
