name: 'STK CLI Action'

description: 'Github Action to install STK CLI'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Install STK CLI - dev
      run: |
        if [[ "$(uname)" = "Linux" ]]; then
          sudo apt update && sudo apt install -y curl unzip git
          curl -fsSL https://stk-cli.dev.stackspot.com/install-dev.sh | bash
          sudo mv /home/runner/.stk-dev/bin/* /usr/local/bin
        elif [[ "$(uname)" = "Darwin" ]]; then
          curl -fsSL https://stk-cli.dev.stackspot.com/install-dev.sh | bash
          sudo mv /Users/runner/.stk-dev/bin/* /usr/local/bin
          mv /usr/local/bin/stk-dev /usr/local/bin/stk
        else
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          vcpkg install curl[tool]
          cd $GITHUB_WORKSPACE
          curl https://stk-cli.dev.stackspot.com/installer/windows/stk-dev.exe --output stk-dev.exe
          ./stk-dev.exe upgrade
          mv stk-dev.exe /bin
        fi
      shell: bash
    
    - name: Show STK CLI  version
      run: stk-dev --version
      shell: bash

    - name: Login to StackSpot Account
      run: stk-dev login --client-id=${{ inputs.client_id }} --client-key=${{ inputs.client_key }} --realm=${{ inputs.realm }}
      shell: bash

branding:
    icon: 'terminal'
    color: 'gray-dark'