name: 'STK CLI Action'

description: 'Github Action to install STK CLI'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash

    - name: Install STK CLI
      run: |
        if [[ "$(uname)" = "Linux" ]]; then
          PACKAGES_TO_INSTALL=""
          if [ "$(which curl)" = "" ]
          then
              PACKAGES_TO_INSTALL="curl "
          fi
          if [ "$(which git)" = "" ]
          then
              PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL git "
          fi
          if [ "$(which jq)" = "" ]
          then
              PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL jq "
          fi
          if [ "$(which zip)" = "" ]
          then
              PACKAGES_TO_INSTALL="$PACKAGES_TO_INSTALL zip "
          fi
          if [ "$PACKAGES_TO_INSTALL" != "" ]
          then
              sudo apt-get install -y $PACKAGES_TO_INSTALL
          else
              echo "All packages already installed !!!"
          fi
          unset PACKAGES_TO_INSTALL

          cd /tmp
          curl -fsSL https://stk.stackspot.com/install.sh | bash
          echo "~/.stk/bin" >> $GITHUB_PATH
        elif [[ "$(uname)" = "Darwin" ]]; then
          cd /tmp
          curl -fsSL https://stk.stackspot.com/install.sh | bash
          sudo mv /Users/runner/.stk/bin/* /usr/local/bin
          echo "~/.stk/bin" >> $GITHUB_PATH
        else
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          vcpkg install curl[tool]
          cd $GITHUB_WORKSPACE
          curl https://stk.stackspot.com/installer/windows/stk.exe --output stk.exe
          ./stk.exe upgrade
          mv stk.exe /bin 
        fi
      shell: bash

    - name: Login to StackSpot Account
      run: stk login --client-id=${{ inputs.client_id }} --client-key=${{ inputs.client_key }} --realm=${{ inputs.realm }}  
      shell: bash

    - name: Show STK CLI version
      run: stk --version
      shell: bash   

branding:
    icon: 'terminal'
    color: 'gray-dark'
