name: Action test MacOS

on:
  push:
    paths:
      - '.github/workflows/action-test-macos.yml'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        os: [macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test changes
        uses: ./
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}

      - name: Show STK CLI version
        run: stk --version
