name: Action test MacOS

on:
  push:
    paths:
      - '.github/workflows/action-test-macos.yml'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run STK CLI installation
        uses: stack-spot/stk-cli-action@dev
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}

      - run: stk-dev --version
      
      - run: stk-dev list workspace

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1