name: Action test Windows

on:
  push:
    paths:
      - '.github/workflows/action-test-windows.yml'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    strategy:
      matrix:
        os: [windows-2019, windows-2022, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run STK CLI installation
        uses: .
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}

      - run: stk --version
        shell: bash
      
