name: Action test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-ubuntu.yml'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run STK CLI installation
        uses: stack-spot/stk-cli-action@fix/installation
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}

      - run: stk --version
      
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
